apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v1j1i4l8v-python
  janus-idp.io/tekton: v1j1i4l8v-python
  backstage.io/kubernetes-id: v1j1i4l8v-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v1j1i4l8v-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
