apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v1j1i4l8v-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v1j1i4l8v-python 
  name: v1j1i4l8v-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: v1j1i4l8v-python 
